add_subdirectory (calculator)
add_subdirectory (sizeof)
add_subdirectory (bits)
add_subdirectory (lab07_1)
add_subdirectory (lab07_2)
add_subdirectory (structures)
add_subdirectory (generator)
add_subdirectory (phone)
add_subdirectory (tasks)
add_subdirectory (bank)
add_subdirectory (lib)
add_subdirectory (matrix)
add_subdirectory (3d)
add_subdirectory (overflow)